#include "buildcfg.h"
#include <KexComm.h>
#include <KexDll.h>
#include <powrprof.h>

EXTERN PKEX_PROCESS_DATA KexData;

typedef enum _WLDP_WINDOWS_LOCKDOWN_MODE {
	WLDP_WINDOWS_LOCKDOWN_MODE_UNLOCKED,
	WLDP_WINDOWS_LOCKDOWN_MODE_TRIAL,
	WLDP_WINDOWS_LOCKDOWN_MODE_LOCKED,
	WLDP_WINDOWS_LOCKDOWN_MODE_MAX
} TYPEDEF_TYPE_NAME(WLDP_WINDOWS_LOCKDOWN_MODE);

typedef struct _VERHEAD {
	WORD				wTotLen;
	WORD				wValLen;
	WORD				wType;
	WCHAR				szKey[(sizeof("VS_VERSION_INFO") + 3) & ~3];
	VS_FIXEDFILEINFO	vsf;
} TYPEDEF_TYPE_NAME(VERHEAD);

#define DEVICE_NOTIFY_CALLBACK 2

typedef enum _WLDP_HOST_ID {
	WLDP_HOST_ID_UNKNOWN,
	WLDP_HOST_ID_GLOBAL,
	WLDP_HOST_ID_VBA,
	WLDP_HOST_ID_WSH,
	WLDP_HOST_ID_POWERSHELL,
	WLDP_HOST_ID_IE,
	WLDP_HOST_ID_MSI,
	WLDP_HOST_ID_ALL,
	WLDP_HOST_ID_MAX
} TYPEDEF_TYPE_NAME(WLDP_HOST_ID);

typedef struct _WLDP_HOST_INFORMATION {
	DWORD        dwRevision;
	WLDP_HOST_ID dwHostId;
	PCWSTR       szSource;
	HANDLE       hSource;
} TYPEDEF_TYPE_NAME(WLDP_HOST_INFORMATION);